@baseUrl = http://localhost:3000

### Login the admin user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}


### Create the admin user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}